image: maven:3.6.2, java:1.8

stages:
  - build

build:
  stage: build
  script: "mvn install -B"

unit-test:
  stage: build
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
